import React, { useEffect, useMemo, useRef, useState } from "react";
import { LiveSpriteAPI } from "../api/liveSpriteApi";
import { resolveArtwork } from "../runtime/stateResolver";
import { NativeCompanion } from "../native/companion";
import { listen } from "@tauri-apps/api/event";
import CharacterRenderer from "../components/CharacterRenderer";

const CALIBRATION_STEPS=["Stay Quiet","Speak Normally","Speak Loudly","Yell"];
const delay=(milliseconds)=>new Promise((resolve)=>setTimeout(resolve,milliseconds));

export default function LiveStudio({ details, reload, reportError }) {
  const session = details?.sessions?.find((item) => item.active);
  const expressionId = session?.currentExpressionId || "";
  const [devices,setDevices]=useState([]);const [audio,setAudio]=useState({running:false,levelDb:-100,voiceState:"idle",deviceName:""});
  const defaults=details?.project?.audioConfig||{};const [voiceConfig,setVoiceConfig]=useState({deviceName:defaults.inputDeviceId||"",noiseGateDb:defaults.noiseGateDb??-55,talkingThresholdDb:defaults.talkingThresholdDb??-38,yellingThresholdDb:defaults.yellingThresholdDb??-18,activationMs:defaults.attackMs??80,releaseMs:defaults.releaseMs??220});
  const [calibration,setCalibration]=useState({step:0,captures:[],recording:false,complete:false});
  const pushedVoice=useRef("");
  const sessionRef=useRef(session);sessionRef.current=session;
  useEffect(()=>{NativeCompanion.listMicrophones().then(setDevices).catch(()=>setDevices([]))},[]);
  useEffect(()=>{const saved=details?.project?.audioConfig;if(!saved)return;setVoiceConfig({deviceName:saved.inputDeviceId||"",noiseGateDb:saved.noiseGateDb??-55,talkingThresholdDb:saved.talkingThresholdDb??-38,yellingThresholdDb:saved.yellingThresholdDb??-18,activationMs:saved.attackMs??80,releaseMs:saved.releaseMs??220})},[details?.project?.id]);
  useEffect(()=>{const timer=setInterval(()=>NativeCompanion.getAudioStatus().then(setAudio).catch(()=>{}),80);return()=>clearInterval(timer)},[]);
  useEffect(()=>{let stop;listen("audio-state",({payload})=>{const active=sessionRef.current;if(!active||active.voiceDetectionEnabled===false)return;let voice=payload;if(voice==="yelling"&&active.yellingEnabled===false)voice="talking";if(pushedVoice.current===voice)return;pushedVoice.current=voice;LiveSpriteAPI.sessions.update(active.id,{currentBaseState:voice,isTalking:voice!=="idle",isYelling:voice==="yelling"}).catch(()=>{});}).then((unlisten)=>{stop=unlisten});return()=>{if(stop)stop()}},[]);
  const preview = useMemo(() => details ? resolveArtwork({ expressionId, voiceState: session?.currentBaseState || "idle", blinking: Boolean(session?.isBlinking), assignments: details.states, assets: details.assets }) : null,
    [details, expressionId, session?.currentBaseState, session?.isBlinking]);
  if (!details) return <section className="panel empty"><h2>Select a project</h2></section>;
  const patch = async (change) => { if (!session) return; try { await LiveSpriteAPI.sessions.update(session.id, change); await reload(); } catch (reason) { reportError(reason?.message || "Unable to update the Live Session."); } };
  const setExpression = (expression) => patch({ currentExpressionId: expression?.id || "", currentExpressionName: expression?.name || "" });
  const recordCalibration=async()=>{if(!audio.running){reportError("Start the microphone before calibration.");return}setCalibration((value)=>({...value,recording:true}));const samples=[];for(let index=0;index<30;index+=1){const status=await NativeCompanion.getAudioStatus();if(Number.isFinite(status.levelDb))samples.push(status.levelDb);await delay(80)}const level=samples.length?samples.reduce((sum,value)=>sum+value,0)/samples.length:-100;const nextCaptures=[...calibration.captures,level];const nextStep=calibration.step+1;if(nextStep===CALIBRATION_STEPS.length){const [quiet,normal,loud,yell]=nextCaptures;let noise=Math.min(normal-6,quiet+5);let talking=Math.max(noise+3,(quiet+normal)/2);let yelling=Math.max(talking+3,(loud+yell)/2);noise=Math.round(noise);talking=Math.round(talking);yelling=Math.round(yelling);const recommended={...voiceConfig,noiseGateDb:noise,talkingThresholdDb:talking,yellingThresholdDb:yelling,activationMs:80,releaseMs:220};setVoiceConfig(recommended);setCalibration({step:0,captures:nextCaptures,recording:false,complete:true});try{await LiveSpriteAPI.projects.update(details.project.id,{audioConfig:{...defaults,inputDeviceId:recommended.deviceName,noiseGateDb:noise,talkingThresholdDb:talking,yellingThresholdDb:yelling,attackMs:80,releaseMs:220}});await reload()}catch(reason){reportError(reason?.message||"Calibration completed, but its settings could not be saved.")}}else setCalibration({step:nextStep,captures:nextCaptures,recording:false,complete:false})};
  return <><header className="page-header"><div><h1>LiveSprite Live</h1><p>Every control updates the authoritative backend Live Session.</p></div><span className={`status ${session ? "online" : "offline"}`}><i />{session ? "Session active" : "Not live"}</span></header>
    {!session ? <section className="panel empty"><div className="brand-mark">✦</div><h2>Ready to go live?</h2><p>Start a Live Session for {details.project.name}.</p><button className="primary compact" onClick={async()=>{await LiveSpriteAPI.sessions.start(details.project.id);await reload();}}>Start Live Session</button></section> : <div className="live-layout">
      <section className="panel live-preview"><div className="character-preview"><CharacterRenderer resolved={preview} visible={session.avatarVisible!==false} alt="Live character" /></div><div className="live-readout"><strong>{session.currentExpressionName || "Normal"}</strong><span>{session.currentBaseState || "idle"}</span></div></section>
      <section className="panel live-controls"><span className="eyebrow">MANUAL CONTROL</span><div className="expression-buttons"><button className={!expressionId?"primary compact":"secondary compact"} onClick={()=>setExpression(null)}>Normal</button>{details.expressions.filter((item)=>item.enabled!==false).map((item)=><button key={item.id} className={expressionId===item.id?"primary compact":"secondary compact"} onClick={()=>setExpression(item)}>{item.name}</button>)}</div><div className="voice-buttons">{["idle","talking","yelling"].map((voice)=><button key={voice} className={session.currentBaseState===voice?"primary compact":"secondary compact"} onClick={()=>patch({currentBaseState:voice,isTalking:voice!=="idle",isYelling:voice==="yelling"})}>{voice}</button>)}</div>
      <div className="audio-panel"><span className="eyebrow">NATIVE MICROPHONE</span><select value={voiceConfig.deviceName} onChange={(e)=>setVoiceConfig({...voiceConfig,deviceName:e.target.value})}><option value="">System default</option>{devices.map((name)=><option key={name}>{name}</option>)}</select><div className="audio-meter"><i style={{width:`${Math.max(0,Math.min(100,(audio.levelDb+80)/80*100))}%`}}/><b className="talk-line" style={{left:`${(voiceConfig.talkingThresholdDb+80)/80*100}%`}}/><b className="yell-line" style={{left:`${(voiceConfig.yellingThresholdDb+80)/80*100}%`}}/></div><div className="audio-readout"><strong>{audio.voiceState.toUpperCase()}</strong><span>{audio.levelDb.toFixed(1)} dB</span></div><div className="threshold-grid">{[["noiseGateDb","Noise Gate"],["talkingThresholdDb","Talking"],["yellingThresholdDb","Yelling"]].map(([key,label])=><label key={key}>{label}<input type="number" value={voiceConfig[key]} onChange={(e)=>setVoiceConfig({...voiceConfig,[key]:Number(e.target.value)})}/></label>)}</div><div className="actions">{audio.running?<><button className="secondary compact" onClick={()=>NativeCompanion.stopVoiceEngine()}>Stop Microphone</button><button className="secondary compact" onClick={()=>NativeCompanion.startVoiceEngine(voiceConfig).catch((reason)=>reportError(String(reason)))}>Reconnect Microphone</button></>:<button className="primary compact" onClick={async()=>{if(!(voiceConfig.noiseGateDb<voiceConfig.talkingThresholdDb&&voiceConfig.talkingThresholdDb<voiceConfig.yellingThresholdDb)){reportError("Noise Gate must be lower than Talking, and Talking must be lower than Yelling.");return}try{await NativeCompanion.startVoiceEngine(voiceConfig);await LiveSpriteAPI.projects.update(details.project.id,{audioConfig:{...defaults,inputDeviceId:voiceConfig.deviceName,noiseGateDb:voiceConfig.noiseGateDb,talkingThresholdDb:voiceConfig.talkingThresholdDb,yellingThresholdDb:voiceConfig.yellingThresholdDb,attackMs:voiceConfig.activationMs,releaseMs:voiceConfig.releaseMs}})}catch(reason){reportError(reason?.message||String(reason))}}}>Start Microphone</button>}</div><div className="calibration"><strong>Guided Calibration</strong><span>{calibration.complete?"Recommendations saved. You can adjust them manually.":`${calibration.step+1}. ${CALIBRATION_STEPS[calibration.step]}`}</span><button className="secondary compact" disabled={calibration.recording||!audio.running} onClick={calibration.complete?()=>setCalibration({step:0,captures:[],recording:false,complete:false}):recordCalibration}>{calibration.recording?"Measuring 2.4 seconds…":calibration.complete?"Calibrate Again":"Measure This Step"}</button>{calibration.captures.length>0&&<small>{calibration.captures.map((value,index)=>`${CALIBRATION_STEPS[index]} ${value.toFixed(1)} dB`).join(" · ")}</small>}</div></div>
      <div className="setting-row"><span>Avatar visibility</span><button className="secondary compact" onClick={()=>patch({avatarVisible:session.avatarVisible===false})}>{session.avatarVisible===false?"Show":"Hide"}</button></div><div className="setting-row"><span>Voice detection</span><button className="secondary compact" onClick={()=>patch({voiceDetectionEnabled:session.voiceDetectionEnabled===false})}>{session.voiceDetectionEnabled===false?"Enable":"Disable"}</button></div><div className="setting-row"><span>Yelling detection</span><button className="secondary compact" onClick={()=>patch({yellingEnabled:session.yellingEnabled===false})}>{session.yellingEnabled===false?"Enable":"Disable"}</button></div><button className="danger compact" onClick={async()=>{await NativeCompanion.stopVoiceEngine();await LiveSpriteAPI.sessions.stop(session.id);await reload();}}>Stop Live Session</button></section>
    </div>}
  </>;
}
