import React, { useMemo, useState } from "react";
import { LiveSpriteAPI } from "../api/liveSpriteApi";
import { NativeCompanion } from "../native/companion";

const PROFILES = [
  [1920,1080,"Horizontal 16:9"],[2560,1440,"QHD 16:9"],[3840,2160,"4K 16:9"],
  [1080,1920,"Vertical 9:16"],[1080,1080,"Square 1:1"],
];

export default function StreamingSetup({ details, reload, reportError }) {
  const source = details?.streams?.find((item) => item.active) || details?.streams?.[0];
  const link = LiveSpriteAPI.streams.link(source);
  const [copied,setCopied]=useState(false);const [busy,setBusy]=useState("");const [software,setSoftware]=useState("obs");const [test,setTest]=useState(null);
  const profile=useMemo(()=>PROFILES.find(([w,h])=>w===(source?.outputWidth||details?.project?.streamingConfig?.outputWidth)&&h===(source?.outputHeight||details?.project?.streamingConfig?.outputHeight))?.[2]||"Custom",[source,details]);
  if(!details)return <section className="panel empty"><h2>Select a project</h2><p>Open a project before configuring its LiveSprite Link.</p></section>;
  const run=async(label,operation)=>{setBusy(label);try{await operation();await reload()}catch(reason){reportError(reason?.message||String(reason))}finally{setBusy("")}};
  const copy=async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch(reason){reportError(`Unable to copy the link: ${reason?.message||reason}`)}};
  const resize=async(width,height)=>run("profile",async()=>{if(source)await LiveSpriteAPI.streams.update(source.id,{outputWidth:width,outputHeight:height,backgroundMode:"transparent"});await LiveSpriteAPI.projects.update(details.project.id,{streamingConfig:{...(details.project.streamingConfig||{}),outputWidth:width,outputHeight:height,backgroundMode:"transparent"}})});
  const testSource=async()=>{setBusy("test");setTest(null);try{setTest(await LiveSpriteAPI.streams.test(source))}catch(reason){reportError(reason?.message||String(reason))}finally{setBusy("")}};
  return <><header className="page-header"><div><h1>LiveSprite Link</h1><p>A render-only source for OBS, TikTok LIVE Studio, and compatible streaming software.</p></div><span className={`status ${source?.active?"online":"offline"}`}><i />{source?.active?"Active":source?"Revoked":"Not created"}</span></header>
    <section className="panel link-panel"><span className="eyebrow">SECURE RENDERER LINK</span>{source?.active?<><div className="link-box"><code>{link}</code><button className="primary compact" onClick={copy}>{copied?"Copied!":"Copy Link"}</button></div><div className="actions"><button className="secondary compact" onClick={()=>NativeCompanion.openExternal(link)}>Open Test Preview</button><button className="secondary compact" disabled={busy==="test"} onClick={testSource}>{busy==="test"?"Testing…":"Test Link"}</button><button className="danger compact" onClick={()=>{if(window.confirm("Regenerate this LiveSprite Link? The old link will stop working immediately."))run("regenerate",()=>LiveSpriteAPI.streams.regenerate(source))}}>Regenerate Link</button><button className="danger compact" onClick={()=>{if(window.confirm("Revoke this LiveSprite Link? Streaming software using it will stop receiving state."))run("revoke",()=>LiveSpriteAPI.streams.revoke(source))}}>Revoke Link</button></div></>:<button className="primary compact" disabled={busy==="create"} onClick={()=>run("create",()=>source?LiveSpriteAPI.streams.regenerate(source):LiveSpriteAPI.streams.create(details.project))}>{source?"Create New Link":"Create LiveSprite Link"}</button>}</section>
    {test&&<section className="panel"><span className="eyebrow">REAL BACKEND TEST</span><div className="test-grid">{Object.entries(test).map(([label,ok])=><div key={label}><span>{label.replace(/[A-Z]/g,(value)=>` ${value}`).replace(/^./,(value)=>value.toUpperCase())}</span><strong className={ok?"pass":"fail"}>{ok?"Pass":"Fail"}</strong></div>)}</div></section>}
    <section className="panel"><span className="eyebrow">OUTPUT PROFILE</span><h2>{profile}</h2><div className="profile-grid">{PROFILES.map(([width,height,label])=><button key={label} className={source?.outputWidth===width&&source?.outputHeight===height?"primary compact":"secondary compact"} onClick={()=>resize(width,height)}>{label}<small>{width}×{height}</small></button>)}</div><div className="custom-profile"><label>Width<input type="number" min="320" max="7680" defaultValue={source?.outputWidth||1920} id="custom-width" /></label><label>Height<input type="number" min="320" max="7680" defaultValue={source?.outputHeight||1080} id="custom-height" /></label><button className="secondary compact" onClick={()=>resize(Number(document.getElementById("custom-width").value),Number(document.getElementById("custom-height").value))}>Save Custom</button></div></section>
    <section className="panel"><span className="eyebrow">STREAMING SETUP</span><div className="software-tabs">{[["obs","OBS Studio"],["tiktok","TikTok LIVE Studio"],["other","Other"]].map(([id,label])=><button key={id} className={software===id?"primary compact":"secondary compact"} onClick={()=>setSoftware(id)}>{label}</button>)}</div>{software==="obs"&&<ol><li>Open OBS Studio and add a Browser Source.</li><li>Paste the LiveSprite Link shown above into its URL field.</li><li>Set Width and Height to the selected output profile.</li><li>Leave custom CSS/background overrides disabled; the renderer is already transparent.</li><li>Open the test preview and confirm voice, expressions, blinking, and visibility.</li></ol>}{software==="tiktok"&&<ol><li>Open TikTok LIVE Studio.</li><li>Add its webpage/link source if that source type is available in your installed version.</li><li>Paste the LiveSprite Link and match the selected output dimensions.</li><li>Confirm transparency and state changes in the source preview before going live.</li></ol>}{software==="other"&&<ol><li>Add a browser, webpage, or URL source in your streaming application.</li><li>Paste the LiveSprite Link.</li><li>Match the selected output profile dimensions.</li><li>Verify the source supports transparent webpage backgrounds.</li></ol>}{source?.active&&<button className="primary compact" onClick={copy}>{copied?"Copied!":"Copy Link"}</button>}</section>
  </>;
}
